# Production override for Racing League Management System
version: '3.8'

services:
  web:
    environment:
      - APACHE_LOG_LEVEL=warn
    volumes:
      # Remove source code volume mapping for production
      - ./uploads:/var/www/html/uploads
      - ./config:/var/www/html/config
    restart: always

  db:
    environment:
      # Use environment variables for production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # Remove init scripts for production if not needed
    restart: always
    # Production database tuning
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=500
      --innodb_buffer_pool_size=1G
      --innodb_log_file_size=256M
      --query_cache_size=64M
      --query_cache_type=1

  # Remove phpMyAdmin in production for security
  # phpmyadmin:
  #   profiles:
  #     - debug

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: racing_league_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - racing_network
    restart: always
    profiles:
      - production